Add vcpkg installation instructions
Maratyszcza/NNPACK pull request #210
Opened 2022-09-14 08:22 UTC by JonLiu1993

nnpack is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for nnpack and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build nnpack, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/nnpack/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

2022-09-14 16:50 UTC, Maratyszcza requested changes

2022-09-14 16:50 UTC, Maratyszcza commented on README.md
> +You can download and install nnpack using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:
"nnpack" -> "NNPACK"

2022-09-14 16:50 UTC, Maratyszcza commented on README.md
> +The nnpack port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/
Ditto

2022-09-15 02:51 UTC, Maratyszcza requested changes

2022-09-15 02:51 UTC, Maratyszcza commented on README.md
>  ### Deep Learning Frameworks
Revert changes to other sections

2022-09-15 03:08 UTC, JonLiu1993 commented on README.md
>  ### Deep Learning Frameworks
Done

2022-09-15 03:10 UTC, Maratyszcza approved these changes

2022-09-15 03:11 UTC, merged